const products = [
  {
    id: "1",
    name: "Men Ring",
    catID: "1",
    img: "http://pngimg.com/uploads/ring/ring_PNG104.png",
    desc: "This is a nice jewel",
    price: "145.95",
    size: "",
  },
  {
    id: "2",
    name: "Men Necklace",
    catID: "2",
    img: "http://pngimg.com/uploads/necklace/necklace_PNG42.png",
    desc: "This is a nice jewel",
    price: "125.0",
    size: "",
  },
  {
    id: "3",
    name: "Men Watch",
    catID: "3",
    img: "https://freepngimg.com/thumb/watch/5-2-watch-png-hd.png",
    desc: "This is a nice jewel",
    price: "150.99",
    size: "",
  },
  {
    id: "4",
    name: "Men Earrings",
    catID: "4",
    img: "http://pngimg.com/uploads/jewelry/jewelry_PNG6823.png",
    desc: "This is a nice jewel",
    price: "199.99",
    size: "",
  },
  {
    id: "5",
    name: "Women Ring",
    catID: "5",
    img: "http://pngimg.com/uploads/ring/ring_PNG104.png",
    desc: "This is a nice jewel",
    price: "125.0",
    size: "",
  },
  {
    id: "6",
    name: "Women Necklace",
    catID: "6",
    img: "http://pngimg.com/uploads/necklace/necklace_PNG42.png",
    desc: "This is a nice jewel",
    price: "145.95",
    size: "",
  },

  {
    id: "7",
    name: "Women Watch",
    catID: "7",
    img: "https://freepngimg.com/thumb/watch/5-2-watch-png-hd.png",
    desc: "This is a nice jewel",
    price: "150.99",
    size: "",
  },

  {
    id: "8",
    name: "Women Earring",
    catID: "8",
    img: "http://pngimg.com/uploads/jewelry/jewelry_PNG6823.png",
    desc: "This is a nice jewel",
    price: "145.95",
    size: "",
  },
  {
    id: "9",
    name: "Men Ring",
    catID: "1",
    img: "http://pngimg.com/uploads/ring/ring_PNG104.png",
    desc: "This is a nice jewel",
    price: "145.95",
    size: "",
  },
  {
    id: "10",
    name: "Men Necklace",
    catID: "2",
    img: "http://pngimg.com/uploads/necklace/necklace_PNG42.png",
    desc: "This is a nice jewel",
    price: "125.0",
    size: "",
  },
  {
    id: "11",
    name: "Men Watch",
    catID: "3",
    img: "https://freepngimg.com/thumb/watch/5-2-watch-png-hd.png",
    desc: "This is a nice jewel",
    price: "150.99",
    size: "",
  },
  {
    id: "12",
    name: "Men Earrings",
    catID: "4",
    img: "http://pngimg.com/uploads/jewelry/jewelry_PNG6823.png",
    desc: "This is a nice jewel",
    price: "199.99",
    size: "",
  },
  {
    id: "13",
    name: "Women Ring",
    catID: "5",
    img: "http://pngimg.com/uploads/ring/ring_PNG104.png",
    desc: "This is a nice jewel",
    price: "125.0",
    size: "",
  },
  {
    id: "14",
    name: "Women Necklace",
    catID: "6",
    img: "http://pngimg.com/uploads/necklace/necklace_PNG42.png",
    desc: "This is a nice jewel",
    price: "145.95",
    size: "",
  },

  {
    id: "15",
    name: "Women Watch",
    catID: "7",
    img: "https://freepngimg.com/thumb/watch/5-2-watch-png-hd.png",
    desc: "This is a nice jewel",
    price: "150.99",
    size: "",
  },

  {
    id: "16",
    name: "Women Earring",
    catID: "8",
    img: "http://pngimg.com/uploads/jewelry/jewelry_PNG6823.png",
    desc: "This is a nice jewel",
    price: "145.95",
    size: "",
  },
];

export default products;
